# Generated by Django 4.2.6 on 2024-02-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='otp',
            field=models.CharField(default='123456', max_length=6),
        ),
    ]
