# Generated by Django 4.2.6 on 2024-02-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0002_mymodel_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='otp',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='email_otp',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='mobile_otp',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
