# Generated by Django 4.2.6 on 2024-03-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0004_mymodel_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
